# Site settings
title: Gaussian Process Approximations Workshop, 2015
email: 
description: > # this means to ignore newlines until "baseurl:"
  Workshop on Gaussian Process Approximations in Copenhagen, Denmark.
baseurl: "/gpa15/" # the subpath of your site, e.g. /blog/
url: "http://gpss.cc" # the base hostname & protocol for your site
twitter_username: datascienceshef
github_username:  SheffieldML
facebook_page: gaussianprocesssummerschool

youtube:
  height: 315
  width: 560

conference:
  hosts:
  - {name: Ole Winther, url: "http://cogsys.imm.dtu.dk/staff/winther/"}
  - {name: DTU, url: "http://www.dtu.dk/"}
  organizers:
  - {name: Ole Winther, url: "http://cogsys.imm.dtu.dk/staff/winther/"}
  - {name: Aki Vehtari, url: "http://becs.aalto.fi/~ave/"}
  - {name: Neil Lawrence, url: "http://inverseprobability.com"}
  name: Workshop on Gaussian Process Approximations
  hosturl: https://sites.google.com/site/gpapprox/home
  location: Copenhagen, Denmark
  year: 2015
  month: May
  dates:
  - {date: 21, day: Thursday, month: May, year: 2015}
  - {date: 22, day: Friday, month: May, year: 2015}
  
# Build settings
markdown: kramdown

