# Site settings
title: Gaussian Process Approximations Workshop, 2015
email: 
description: > # this means to ignore newlines until "baseurl:"
  Workshop on Gaussian Process Approximations in Copenhagen, Denmark.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://gpss.cc" # the base hostname & protocol for your site
twitter_username: datascienceshef
github_username:  SheffieldML
facebook_page: gaussianprocesssummerschool

youtube:
  height: 315
  width: 560

conference:
  hosts:
  - {name: Ole Winther, url: "http://cogsys.imm.dtu.dk/staff/winther/"}
  organizers:
  - {name: Neil Lawrence, url: "http://inverseprobability.com"}
  - {name: Andreas Damianou, url: "http://javiergonzalezh.github.io/"}
  - {name: John Quinn, url: "http://sheffieldml.github.io"}
  name: Workshop on Gaussian Process Approximations
  hosturl: https://sites.google.com/site/dekutdatascienceworkshop2015/
  location: Dedan Kimathi University of Technlogy, Nyeri, Kenya
  year: 2015
  month: June
  dates:
  - {date: 15, day: Monday, month: June, year: 2015}
  - {date: 16, day: Tuesday, month: June, year: 2015}
  - {date: 17, day: Wednesday, month: June, year: 2015}
  
# Build settings
markdown: kramdown

